config/routes.rb
Tech2me::Application.routes.draw do

  root to: 'questions#index'

  get "/questions", to: "questions#index", as: :questions
  post "/questions", to: "questions#create"
  get "questions/new", to: "questions#new", as: :new_question

  resources :questions, only: [:show, :edit, :update]
  resources :answers, only: [:create]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :body, :question_id, :author
  validates :body, :presence => true
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :body, :user
  validates :title, :body, presence: true
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  attr_accessible :email, :password
  has_many :questions
  has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    current_question = Question.find(params[:answer][:question_id])
    @answer = current_question.answers.build(params[:answer])
    @answer.user = current_user
    if @answer.save
      redirect_to question_path(@answer.question)
    else
      flash[:error] = "Something went wrong"
      redirect_to question_path(@answer.question)
    end
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update_attributes(params[:answer])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
    @question = Question.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(params[:question])
    if @question.save
      p "YAY"
    else
      p "NOOOOOOOOOOOOO"
    end
    render :json => render_to_string(:partial => 'question', :locals => {:question => @question }).to_json
  end

  def show
    @answer = Answer.new
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    question = Question.find(params[:id])
    question.update_attributes(params[:question])
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<p>
  <strong>Commenter:</strong>
  <%= answer.author %>
</p>
<p>
  <strong>Answer:</strong>
  <%= answer.answer %>
</p>

app/views/answers/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </p>
  <p>
    <%= f.submit :Submit %>
  </p>
<% end %>

app/views/answers/index.html.erb
<% if @user_answers %>
  <h1> HERE ARE YOUR ANSWERS </h1>
  <% @user_answers.each do |answer| %>
  <ul> Author Name You Used: <%= answer.author %>
    <li> Answer You provided: <%= answer.body %> </li>
  </ul>
  <% end %>
<% else %>
  <h2> <%= @no_answers %> </h2>
<% end %>

app/views/layouts/_authentication.html.erb
<% if signed_in? %>
  <span id='new_question_btn'><%= link_to 'New Question', new_question_path(@question) %></span>

  Signed in as: <%= current_user.email %>
  <%= link_to 'Sign out', sign_out_path, :method => :delete, :class => 'sign_in' %>
<% else %>
  <%= link_to 'Sign in', sign_in_path, :class => 'sign_in' %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <%= link_to 'tech2me', root_path, id: "logo" %>
  <% if signed_in? %>
  <p> Signed in as: <%= current_user.email %> <p>
    <%= link_to 'Sign out', sign_out_path, :method => :delete, :class => 'sign_in' %>
    <% else %>
    <%= link_to 'Sign in', sign_in_path, :class => 'sign_in' %>
    <% end %>
  </br>
  <div id="flash">
    <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>

  <span id='new_question_btn'><%= link_to 'New Question', new_question_path(@question), class: 'fun-links' %></span>
</br>
<% if current_user %>
<%= link_to 'View your past Answers', answers_path, class: 'fun-links' %>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tech2me</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='container'>
    <nav>

    <%= link_to 'tech2me', root_path, id: "logo" %>

    <%= render 'layouts/authentication' %>

  </nav>

  <%= yield %>

  <%= flash[:error] %>

</div>
</body>
</html>

app/views/questions/_form.html.erb
<p>Ask a Question:</p>

<%= form_for @question, :remote => true do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br>
  <%= f.label :question %>:
  <%= f.text_field :body %><br>
  <div class='submit-button'>
    <%= f.submit "Ask!" %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div class="question_card">
  <li class='question_title'><%= link_to question.title, question_path(question) %></li>
  <p><%= question.body%></p>
</div>

app/views/questions/edit.html.erb
<%= form_for @question do |f| %>
  <%= f.text_field :title, class: "edit_title"  %>
  <%= f.text_area :body %>
  <%= f.submit "edit", class: "submit" %>
<% end %>

app/views/questions/index.html.erb
<div id='question_pop_up' class='hidden'>
  <%= render 'form' %>
</div>

<ul id='question_area'>
  <% @questions.each do |question| %>
    <%= render 'question', question: question %>
  <% end %>
</ul>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<br/>
<p><%= @question.body %></p>

<%= link_to 'back', root_path %>
<%= link_to 'edit', edit_question_path(@question) %>

<h1>Add a new answer</h1>

<%= form_for @answer do |f| %>
  <%= hidden_field_tag :question_id, value: @question.id %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body, "Answer" %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

  <ul>
    <% @answers.each do |answer| %>
      <li>Author: <%= answer.author %></li>
      <li>answer: <%= answer.body %></li>
    <% end %>
  </ul>

app/views/users/index.html.erb
sweet file